spring:
  config:
    import: "sm://"
  application:
    name: career-board
  datasource:
    url: jdbc:postgresql:///career-board
    username: career-board
    password: "${sm://projects/553556926651/secrets/pg-dev-password/versions/1}"
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: career-crew:us-central1:career-board-instance
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

  cloud:
    gcp:
      secretmanager:
        enabled: true
        project-id: career-crew
        secret-name-prefix: 'sm://'
      sql:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


greeting: "${sm://projects/553556926651/secrets/greeting/versions/1}"